    datasource:
      url: 
      username: 
      password:
      driverClassName: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true



  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB



#  jwt.secret :

  logging:
    level:
      com:
        teamjo:
          techeermarket: DEBUG

  cloud:
    aws:
      credentials:
        accessKey: 
        secretKey:
      s3:
        bucket: 
      region:
        static:
      stack:
        auto: false


