spring:
  datasource:
    url: jdbc:postgresql://${CLOUD_AWS_DB_HOST}:5432/${CLOUD_AWS_DB_DATABASE_NAME}
    username: ${CLOUD_AWS_DB_USERNAME}
    password: ${CLOUD_AWS_DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  #    datasource:
  #      url: jdbc:postgresql://localhost:5432/techeermarket
  #      username: postgres
  #      password: 1234
  #      driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

servlet:
  multipart:
    max-file-size: 1000MB
    max-request-size: 1000MB

jwt.secret: kJlkhRU-b-p3nwYgbeNpgVii1rssccUKOP4yaUjeHbM

logging:
  level:
    com:
      teamjo:
        techeermarket: DEBUG

cloud:
  aws:
    credentials:
      accessKey: ${CLOUD_AWS_ACCESS_KEY_ID}
      secretKey: ${CLOUD_AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKETNAME}
    region:
      static: ${CLOUD_AWS_S3_REGION}
    stack:
      auto: false
